### ISSUE TITLE
Add info component on gas prices in the onboarding

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/aragon#28]
Add a warning info component in the "Review information" section before launching your organization where to inform the organization administrator about gas prices and how to set up a moderate gas price for a smooth setup before clicking on moving onto the final step.

There are two versions for this message depending on whether the user's Ethereum Provider is or isn't MetaMask. Text specifications [available here](https://www.notion.so/autark/Design-specifications-c3c1946692904ba09eb7e6682dee1d02#59944527b7f7484faceaae2d2e7c9fe9). Link would direct users to the troubleshooting Help Scout documentation.

[Figma file available here.](https://www.figma.com/file/Q446JiJ7R2rWy1zUwak2NP/Onboarding?node-id=152%3A571)

![D 1 0 - Review information](https://user-images.githubusercontent.com/28843778/69146123-707d7680-0acf-11ea-93db-099c864028d0.png)

**Comment by stellarmagnet** [comment]
The thing I'm worried about with the warning on this screen, is that the user may be confused and try to adjust the gas price there - they won't always click the documentation, I assume some may try before. They won't be able to actually update the gas price until they hit "launch organization". We may want to describe that more so they don't fumble to change the price while they are on this screen.

**Comment by javieralaves** [comment]
@stellarmagnet Good point, we could instead suggest the user to activate MetaMask's "Advanced gas controls" so that the gas price can be adjusted right before submitting each transaction. For this to be effective, we should also make clear what the reasonable gas price should be.

**Comment by stellarmagnet** [comment]
@jayalaves no, they don't have to enable that and we shouldn't instruct them to turn it on. The way to update the gas without enabling the advanced feature is the hit the "EDIT" link in the Gas Fee section. I was just saying, we need better language so the user knows that the gas price cannot be edited until the MetaMask extension is triggered, which happens after the user hits "Launch Organization"

**Comment by stellarmagnet** [comment]
Maybe something like...

> Your current gas price is set to 1 Gwei, which means your organization might take about 10 to 15 minutes to set up. You can change this in your MetaMask extension/Ethereum provider as soon as you click the "Launch Organization" button below. Learn more about gas prices and how to adjust them in the documentation.

**Comment by sohkai** [comment]
I don't know about adding a warning here; I'd just increase the default gas price we use based on the API call and place a warning in the signing step with a link to https://ethgas.io/.

**Comment by stellarmagnet** [comment]
@sohkai good call - I was on the fence with if we needed this as well, since we are going down the gas API route.

**Comment by stellarmagnet** [comment]
@sohkai I'm not sure about that link though, did you mean https://ethgasstation.info/ ? Even with that, the estimate won't be accurate. I think linking to the Aragon help docs would be better (a new page), but we can chat on that more in the #29 ticket

**Comment by sohkai** [comment]
ethgas.io is page I usually give people if they need to understand gas, but yes, in this case, we could provide other links if we wanted to direct users to places to check the current gas market. Having a article in the helpscout docs (see [aragon/help](https://github.com/aragon/help)) that aggregates those links makes sense.

**Comment by javieralaves** [comment]
Thank you everyone for your feedback on this issue – I think we have enough of a common vision as to how to move forward on this particular topic – following @sohkai's recommendation:
> I'd just increase the default gas price we use based on the API call and place a warning in the signing step

And we can continue the conversation in #29, as that's where there's still some more inputs we can discuss on potential changes or enhancements to the onboarding process.
