### ISSUE TITLE
Update Onboarding template info component

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/aragon#32]
Info component

- This component should take on a “warning” style, as per the designs.
- The text should be updated, as per the designs. The hyperlink should open this link in a new tab, where we’ll eventually have further related to improving the onboarding experience.
- Only display the sentence that says “Additionally, do not use the "Speed Up" MetaMask feature, otherwise it will result in configuration errors.” if the Ethereum provider is MetaMask

[Design reference](https://www.figma.com/file/Q446JiJ7R2rWy1zUwak2NP/Onboarding?node-id=176%3A85)

**Comment by e18r** [comment]
> The hyperlink should open this link in a new tab, where we’ll eventually have further related to improving the onboarding experience.

What hyperlink? I can't find it here, or in Figma, or in the [specs](https://www.notion.so/autark/Design-specifications-c3c1946692904ba09eb7e6682dee1d02)

cc @javieralaves

**Comment by javieralaves** [comment]
@e18r At the end of the help component there is a string of text that appears with the link style. That’s what I’m referring to

**Comment by stellarmagnet** [comment]
He is asking for the actual hyperlink, which I don’t think exists until we
get the Help Scout merged

**Comment by javieralaves** [comment]
_@stellarmagnet Removed our previous comments from the thread to clear it up. Thanks for the clarification!_

@e18r We need to submit a PR to Aragon's Help Scout repository to merge a page that will eventually be the one we want to have linked. Until then, we can simply point [at this page](https://help.aragon.org/category/24-troubleshooting).

**Comment by e18r** [comment]
> Only display the sentence that says “Additionally, do not use the "Speed Up" MetaMask feature, otherwise it will result in configuration errors.” if the Ethereum provider is MetaMask

@Quazia @javieralaves are you sure Metamask is the only provider that has speed up capabilities? It seems like a pretty generic feature to me
