### ISSUE TITLE
Ability to set a custom aragon apm URI for home tab

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/aragon#5]
Currently the home app routes to the root URL for the application, instead we want to provide the ability to route to a specific application. This routing should default to the current home application, and only become active if a home app is specifically set.
The routing is currently handled in [/src/routing.js#L90](https://github.com/aragon/aragon/blob/a1125a73d2027edd2e63a6d6f0175f58830cc560/src/routing.js#L90).
This will require modifying that function to leverage a client or contract level setting for how to route home, and providing hooks to change this setting elsewhere in the client.
In order to make those changes, the [local-settings.js](https://github.com/aragon/aragon/blob/9072e3b90d3733f48b8b08ed7ce3293c1e19d068/src/local-settings.js) file will need to accommodate a _home app_ selector. This will also require changing the [settings component](https://github.com/aragon/aragon/blob/9072e3b90d3733f48b8b08ed7ce3293c1e19d068/src/apps/Settings/Settings.js) to provide the correct UI to make these changes.
Since the routing.js function is called from the wrapper, it would be best to handle the loading of local state settings in the wrapper so that no state needs to be loaded in the routing.js file. Using a contract based solution we would pull this information through subscription to the wrapper, which is detailed below.
Once all of this is taken care of we'll have the ability to set a new home app locally but in order for the change to persist it needs to be performed on the kernel.

To have the home app URI persist it makes the most sense to add a function/field to the kernel contract similar to how [setting a recovery vault is handled](https://github.com/aragon/aragonOS/blob/dev/contracts/kernel/Kernel.sol#L158) The exact implementation depends on how we want to handle subscription to this information as detailed below.
In order to get the URI set and pulled from the kernel it will be necessary to interact with the contract sets through the wrapper (The one created in App.js not the component) similar to how [app upgrades are handled](https://github.com/aragon/aragon/blob/8542ba3af3c6245b0b39599e1be351c7d5169eb8/src/apps/AppCenter/AppCenter.js#L44). In a standard DAO this transaction routing should be fairly straight forward but using the correct path is still important to accommodate for vote based home URI changes or more complex permission structures. The correct handler for an update to the home app URI will also need to be added in the wrapper initialization in [App.js](https://github.com/aragon/aragon/blob/a67a7600ff88d03d4587d8d9a8a55dd29745e210/src/App.js#L217) and the [changes will need to be subscribed to](https://github.com/aragon/aragon/blob/ba10d279861470ba10d62753f50a1dca56d4f5f6/src/aragonjs-wrapper.js#L192)

Update: Since we've determined that making a kernel level change is not the best course of action the home app setting (and all other organization settings) will need to be stored in a contract-only storage application (we may want to eventually build out a UI, but for now just the client level UI should be sufficient). Since we're handling it this way we can handle the custom home tab through consumption of external contract events without the need to make modifications to aragon.js. If the storage app is not loaded, the settings changes should prompt the user to install this application. If the storage app is loaded the wrapper should parse a uniquely identified storage element based on storage events and interpret it as the home app.

The storage application should generate events of the form `Registered(Bytes32 key)` and for the initial home app settings we can use `keccak256("DEFAULT_HOME_APP")` as the key.

~Since there isn’t an observable to subscribe to in aragon.js currently we either need to: create another observable to handle the change of a home app or, attach a flag to the app instance that is being used for the home application which we can handle when we respond to changes in the application stream.~

### Design

- Add a "Home Page" section in the Settings app, below the Organization address section. Here, the user can select another home app from a dropdown menu. 
- There should be an option "Use the default" which will be the existing home app and hence the default option that is selected.
- If they select another app, then the existing "Home" app will not be displayed.
- There will be an additional input where the user can rename the tab. By default this will be Home. This means if the user chooses "Voting" then the tab name will show up as Home unless they rename the tab.

![image](https://user-images.githubusercontent.com/2584493/58388001-bffb5200-8018-11e9-8b27-e9a7a1655096.png)

**Comment by ottodevs** [comment]
The first approach is ready to review at #10
