### ISSUE TITLE
Connect client to Storage app

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/aragon#7]
Since we've determined that making a kernel level change is not the best course of action the home app setting (and all other organization settings) will need to be stored in a contract-only storage application (we may want to eventually build out a UI, but for now just the client level UI should be sufficient). When the client parses through the connected apps, it will need to save the _default_ (when multiple apps of the same type are installed a default application can be set, use this one) storage application and provide this in the react state. A function will then need to be passed into the settings component that calls the Storage function `registerData(bytes32 key, string value)` on the storage application.

**Comment by ottodevs** [comment]
Addressed at #10 pending review

**Comment by Schwartz10** [comment]
https://github.com/AutarkLabs/aragon/blob/feat/storage-tab/src/storage/storage-wrapper.js is a relatively robust way of providing the smart contract to the rest of the client.

We're going to wrap the smart contract methods in a call that will exposed by [this hook](https://github.com/AutarkLabs/aragon/blob/feat/storage-tab/src/hooks.js#L308)
